In [2]:
import pandas as pd

In [ ]:
df=pd.read_csv('updat.csv')
df.head()

In [26]:
def lalong(location):
    lat=0
    lon=0
    num=0
    if(location=='Guwahati'):
        lat=26.148043
        lon=91.731377
        num=1
    if(location=='Hyderabad'):
        lat=17.387140 
        lon=78.491684
        num=2
    if(location=='Delhi'):
        lat=28.653229 
        lon=77.308601
        num=3
    if(location=='Chandigarh'):
        lat=30.741482 
        lon=76.768066
        num=4
    if(location=='Jaipur'):
        lat=26.922070 
        lon=75.778885
        num=5
    if(location=='Nagpur'):
        lat=21.146633 
        lon=79.088860
        num=6
    if(location=='Kolkata'):
        lat=22.572645 
        lon=88.363892
        num=7
    if(location=='Kanpur'):
        lat=26.449923 
        lon=80.331871
        num=8
    if(location=='Agra'):
        lat=27.176670
        lon=78.008072
        num=9
    if(location=='Kochi'):
        lat=9.939093 
        lon=76.270523
        num=10
    if(location=='Vishakapatnam'):
        lat=17.686815 
        lon=83.218483
        num=11
    if(location=='Bangalore'):
        lat=12.972442 
        lon=77.580643
        num=12
    if(location=='Chennai'):
        lat=13.067439 
        lon=80.237617
        num=13
    if(location=='Ahmedabad'):
        lat=23.033863 
        lon=72.585022
        num=14
    if(location=='Lucknow'):
        lat=26.850000 
        lon=80.949997
        num=15
    if(location=='Ludhiana'):
        lat=30.900965 
        lon=75.857277
        num=16
    if(location=='Jodhpur'):
        lat=26.263863 
        lon=73.008957
        num=17
    if(location=='Navi Mumbai'):
        lat=19.076090 
        lon=72.877426
        num=18
    if(location=='Pune'):
        lat=18.516726 
        lon=73.856255
        num=19
    if(location=='Nashik'):
        lat=19.997454 
        lon=73.789803
        num=20
    if(location=='Kota'):
        lat=25.1695181 
        lon=75.854838
        num=21
    if(location=='Gobindgarh'):
        lat=30.663738 
        lon=76.300042
        num=22
    if(location=='Jalandhar'):
        lat=31.326015 
        lon=75.576180
        num=23
    if(location=='Alwar'):
        lat=27.560932
        lon=76.625015
        num=24
    if(location=='Udaipur'):
        lat=24.571270 
        lon=73.691544
        num=25
    if(location=='Thane'):
        lat=19.218330
        lon=72.978088
        num=26
    if(location=='Howrah'):
        lat=22.595770 
        lon=88.263641
        num=27
    if(location=='Parwanoo'):
        lat=30.8381 
        lon=76.9585
        num=28
    if(location=='Aizwal'):
        lat=23.727106 
        lon=92.717636
        num=29
    if(location=='DANKUNI'):
        lat=22.671679 
        lon=88.300209
        num=30
    if(location=='Faridkot'):
        lat=30.678186 
        lon=74.739555
        num=31
    if(location=='Kothur'):
        lat=17.1474 
        lon=78.2889
        num=32
    if(location=='Hoshiarpur'):
        lat=31.527355 
        lon=75.913673
        num=33
    if(location=='Bidar'):
        lat=17.920000 
        lon=77.519722
        num=34
    if(location=='Mathura'):
        lat=27.492413  
        lon=77.673676
        num=35
    if(location=='Konark'):
        lat=20.021883 
        lon=73.849785
        num=36
    if(location=='Chandarpur'):
        lat=19.970324
        lon=79.303360
        num=37
    if(location=='Imphal'):
        lat=24.813967 
        lon=93.950279
        num=38
    if(location=='Keonjhar'):
        lat=21.628933 
        lon=85.581688
        num=39
    if(location=='Silchar'):
        lat=24.833946 
        lon=92.779282
        num=40
    if(location=='Umsning'):
        lat=25.752899 
        lon=91.894455
        num=41
    if(location=='Bijapur'):
        lat=16.827545 
        lon=75.725327
        num=42
    if(location=='Puri'):
        lat=19.817743 
        lon=85.828629
        num=43
    if(location=='MORBI'):
        lat=22.811989 
        lon=70.823616
        num=44
    if(location=='Saharanpur'):
        lat=29.959694 
        lon=77.549057
        num=45
    if(location=='Baruipur'):
        lat=22.3668 
        lon=88.4373
        num=46
    if(location=='Naharlagun'):
        lat=27.1046 
        lon=93.6953
        num=47
    if(location=='Itanagar'):
        lat=27.0869 
        lon=93.6086
        num=48
    if(location=='Tuticorin'):
        lat=8.7642
        lon=78.1348
        num=49
    if(location=='Chittorgarh'):
        lat=24.879999 
        lon=74.629997
        num=50
    if(location=='Noida'):
        lat=28.535517 
        lon=77.391029
        num=51
    if(location=='Ghaziabad'):
        lat=28.6692
        lon=77.4538
        num=52
    if(location=='Nizamabad'):
        lat=18.6725 
        lon=78.0941
        num=53
    if(location=='VAPI'):
        lat=20.385181 
        lon=72.911453
        num=54
    if(location=='Sarigam'):
        lat=20.290300 
        lon=72.852700
        num=55
    if(location=='Bhuj'):
        lat=23.265671 
        lon=69.676903
        num=56
    if(location=='SANAND'):
        lat=22.982460 
        lon=72.378578
        num=57
    if(location=='Khajuraho'):
        lat=24.851900 
        lon=79.923000
        num=58
    if(location=='Gangtok'):
        lat=27.325757 
        lon=88.698277
        num=59
    if(location=='Dharuhera'):
        lat=28.205523 
        lon=76.795311
        num=60
    return lat

In [29]:
df['latitude']=df['location'].apply(lalong)
data= df[['latitude','location']]
data.head()

   latitude   location
0  17.38714  Hyderabad
1  17.38714  Hyderabad
2  17.38714  Hyderabad
3  17.38714  Hyderabad
4  17.38714  Hyderabad

In [31]:
def lalong(location):
    lat=0
    lon=0
    num=0
    if(location=='Guwahati'):
        lat=26.148043
        lon=91.731377
        num=1
    if(location=='Hyderabad'):
        lat=17.387140 
        lon=78.491684
        num=2
    if(location=='Delhi'):
        lat=28.653229 
        lon=77.308601
        num=3
    if(location=='Chandigarh'):
        lat=30.741482 
        lon=76.768066
        num=4
    if(location=='Jaipur'):
        lat=26.922070 
        lon=75.778885
        num=5
    if(location=='Nagpur'):
        lat=21.146633 
        lon=79.088860
        num=6
    if(location=='Kolkata'):
        lat=22.572645 
        lon=88.363892
        num=7
    if(location=='Kanpur'):
        lat=26.449923 
        lon=80.331871
        num=8
    if(location=='Agra'):
        lat=27.176670
        lon=78.008072
        num=9
    if(location=='Kochi'):
        lat=9.939093 
        lon=76.270523
        num=10
    if(location=='Vishakapatnam'):
        lat=17.686815 
        lon=83.218483
        num=11
    if(location=='Bangalore'):
        lat=12.972442 
        lon=77.580643
        num=12
    if(location=='Chennai'):
        lat=13.067439 
        lon=80.237617
        num=13
    if(location=='Ahmedabad'):
        lat=23.033863 
        lon=72.585022
        num=14
    if(location=='Lucknow'):
        lat=26.850000 
        lon=80.949997
        num=15
    if(location=='Ludhiana'):
        lat=30.900965 
        lon=75.857277
        num=16
    if(location=='Jodhpur'):
        lat=26.263863 
        lon=73.008957
        num=17
    if(location=='Navi Mumbai'):
        lat=19.076090 
        lon=72.877426
        num=18
    if(location=='Pune'):
        lat=18.516726 
        lon=73.856255
        num=19
    if(location=='Nashik'):
        lat=19.997454 
        lon=73.789803
        num=20
    if(location=='Kota'):
        lat=25.1695181 
        lon=75.854838
        num=21
    if(location=='Gobindgarh'):
        lat=30.663738 
        lon=76.300042
        num=22
    if(location=='Jalandhar'):
        lat=31.326015 
        lon=75.576180
        num=23
    if(location=='Alwar'):
        lat=27.560932
        lon=76.625015
        num=24
    if(location=='Udaipur'):
        lat=24.571270 
        lon=73.691544
        num=25
    if(location=='Thane'):
        lat=19.218330
        lon=72.978088
        num=26
    if(location=='Howrah'):
        lat=22.595770 
        lon=88.263641
        num=27
    if(location=='Parwanoo'):
        lat=30.8381 
        lon=76.9585
        num=28
    if(location=='Aizwal'):
        lat=23.727106 
        lon=92.717636
        num=29
    if(location=='DANKUNI'):
        lat=22.671679 
        lon=88.300209
        num=30
    if(location=='Faridkot'):
        lat=30.678186 
        lon=74.739555
        num=31
    if(location=='Kothur'):
        lat=17.1474 
        lon=78.2889
        num=32
    if(location=='Hoshiarpur'):
        lat=31.527355 
        lon=75.913673
        num=33
    if(location=='Bidar'):
        lat=17.920000 
        lon=77.519722
        num=34
    if(location=='Mathura'):
        lat=27.492413  
        lon=77.673676
        num=35
    if(location=='Konark'):
        lat=20.021883 
        lon=73.849785
        num=36
    if(location=='Chandarpur'):
        lat=19.970324
        lon=79.303360
        num=37
    if(location=='Imphal'):
        lat=24.813967 
        lon=93.950279
        num=38
    if(location=='Keonjhar'):
        lat=21.628933 
        lon=85.581688
        num=39
    if(location=='Silchar'):
        lat=24.833946 
        lon=92.779282
        num=40
    if(location=='Umsning'):
        lat=25.752899 
        lon=91.894455
        num=41
    if(location=='Bijapur'):
        lat=16.827545 
        lon=75.725327
        num=42
    if(location=='Puri'):
        lat=19.817743 
        lon=85.828629
        num=43
    if(location=='MORBI'):
        lat=22.811989 
        lon=70.823616
        num=44
    if(location=='Saharanpur'):
        lat=29.959694 
        lon=77.549057
        num=45
    if(location=='Baruipur'):
        lat=22.3668 
        lon=88.4373
        num=46
    if(location=='Naharlagun'):
        lat=27.1046 
        lon=93.6953
        num=47
    if(location=='Itanagar'):
        lat=27.0869 
        lon=93.6086
        num=48
    if(location=='Tuticorin'):
        lat=8.7642
        lon=78.1348
        num=49
    if(location=='Chittorgarh'):
        lat=24.879999 
        lon=74.629997
        num=50
    if(location=='Noida'):
        lat=28.535517 
        lon=77.391029
        num=51
    if(location=='Ghaziabad'):
        lat=28.6692
        lon=77.4538
        num=52
    if(location=='Nizamabad'):
        lat=18.6725 
        lon=78.0941
        num=53
    if(location=='VAPI'):
        lat=20.385181 
        lon=72.911453
        num=54
    if(location=='Sarigam'):
        lat=20.290300 
        lon=72.852700
        num=55
    if(location=='Bhuj'):
        lat=23.265671 
        lon=69.676903
        num=56
    if(location=='SANAND'):
        lat=22.982460 
        lon=72.378578
        num=57
    if(location=='Khajuraho'):
        lat=24.851900 
        lon=79.923000
        num=58
    if(location=='Gangtok'):
        lat=27.325757 
        lon=88.698277
        num=59
    if(location=='Dharuhera'):
        lat=28.205523 
        lon=76.795311
        num=60
    return lon

In [32]:
df['longitude']=df['location'].apply(lalong)
data= df[['longitude','location']]
data.head()

   longitude   location
0  78.491684  Hyderabad
1  78.491684  Hyderabad
2  78.491684  Hyderabad
3  78.491684  Hyderabad
4  78.491684  Hyderabad

In [33]:
def lalong(location):
    lat=0
    lon=0
    num=0
    if(location=='Guwahati'):
        lat=26.148043
        lon=91.731377
        num=1
    if(location=='Hyderabad'):
        lat=17.387140 
        lon=78.491684
        num=2
    if(location=='Delhi'):
        lat=28.653229 
        lon=77.308601
        num=3
    if(location=='Chandigarh'):
        lat=30.741482 
        lon=76.768066
        num=4
    if(location=='Jaipur'):
        lat=26.922070 
        lon=75.778885
        num=5
    if(location=='Nagpur'):
        lat=21.146633 
        lon=79.088860
        num=6
    if(location=='Kolkata'):
        lat=22.572645 
        lon=88.363892
        num=7
    if(location=='Kanpur'):
        lat=26.449923 
        lon=80.331871
        num=8
    if(location=='Agra'):
        lat=27.176670
        lon=78.008072
        num=9
    if(location=='Kochi'):
        lat=9.939093 
        lon=76.270523
        num=10
    if(location=='Vishakapatnam'):
        lat=17.686815 
        lon=83.218483
        num=11
    if(location=='Bangalore'):
        lat=12.972442 
        lon=77.580643
        num=12
    if(location=='Chennai'):
        lat=13.067439 
        lon=80.237617
        num=13
    if(location=='Ahmedabad'):
        lat=23.033863 
        lon=72.585022
        num=14
    if(location=='Lucknow'):
        lat=26.850000 
        lon=80.949997
        num=15
    if(location=='Ludhiana'):
        lat=30.900965 
        lon=75.857277
        num=16
    if(location=='Jodhpur'):
        lat=26.263863 
        lon=73.008957
        num=17
    if(location=='Navi Mumbai'):
        lat=19.076090 
        lon=72.877426
        num=18
    if(location=='Pune'):
        lat=18.516726 
        lon=73.856255
        num=19
    if(location=='Nashik'):
        lat=19.997454 
        lon=73.789803
        num=20
    if(location=='Kota'):
        lat=25.1695181 
        lon=75.854838
        num=21
    if(location=='Gobindgarh'):
        lat=30.663738 
        lon=76.300042
        num=22
    if(location=='Jalandhar'):
        lat=31.326015 
        lon=75.576180
        num=23
    if(location=='Alwar'):
        lat=27.560932
        lon=76.625015
        num=24
    if(location=='Udaipur'):
        lat=24.571270 
        lon=73.691544
        num=25
    if(location=='Thane'):
        lat=19.218330
        lon=72.978088
        num=26
    if(location=='Howrah'):
        lat=22.595770 
        lon=88.263641
        num=27
    if(location=='Parwanoo'):
        lat=30.8381 
        lon=76.9585
        num=28
    if(location=='Aizwal'):
        lat=23.727106 
        lon=92.717636
        num=29
    if(location=='DANKUNI'):
        lat=22.671679 
        lon=88.300209
        num=30
    if(location=='Faridkot'):
        lat=30.678186 
        lon=74.739555
        num=31
    if(location=='Kothur'):
        lat=17.1474 
        lon=78.2889
        num=32
    if(location=='Hoshiarpur'):
        lat=31.527355 
        lon=75.913673
        num=33
    if(location=='Bidar'):
        lat=17.920000 
        lon=77.519722
        num=34
    if(location=='Mathura'):
        lat=27.492413  
        lon=77.673676
        num=35
    if(location=='Konark'):
        lat=20.021883 
        lon=73.849785
        num=36
    if(location=='Chandarpur'):
        lat=19.970324
        lon=79.303360
        num=37
    if(location=='Imphal'):
        lat=24.813967 
        lon=93.950279
        num=38
    if(location=='Keonjhar'):
        lat=21.628933 
        lon=85.581688
        num=39
    if(location=='Silchar'):
        lat=24.833946 
        lon=92.779282
        num=40
    if(location=='Umsning'):
        lat=25.752899 
        lon=91.894455
        num=41
    if(location=='Bijapur'):
        lat=16.827545 
        lon=75.725327
        num=42
    if(location=='Puri'):
        lat=19.817743 
        lon=85.828629
        num=43
    if(location=='MORBI'):
        lat=22.811989 
        lon=70.823616
        num=44
    if(location=='Saharanpur'):
        lat=29.959694 
        lon=77.549057
        num=45
    if(location=='Baruipur'):
        lat=22.3668 
        lon=88.4373
        num=46
    if(location=='Naharlagun'):
        lat=27.1046 
        lon=93.6953
        num=47
    if(location=='Itanagar'):
        lat=27.0869 
        lon=93.6086
        num=48
    if(location=='Tuticorin'):
        lat=8.7642
        lon=78.1348
        num=49
    if(location=='Chittorgarh'):
        lat=24.879999 
        lon=74.629997
        num=50
    if(location=='Noida'):
        lat=28.535517 
        lon=77.391029
        num=51
    if(location=='Ghaziabad'):
        lat=28.6692
        lon=77.4538
        num=52
    if(location=='Nizamabad'):
        lat=18.6725 
        lon=78.0941
        num=53
    if(location=='VAPI'):
        lat=20.385181 
        lon=72.911453
        num=54
    if(location=='Sarigam'):
        lat=20.290300 
        lon=72.852700
        num=55
    if(location=='Bhuj'):
        lat=23.265671 
        lon=69.676903
        num=56
    if(location=='SANAND'):
        lat=22.982460 
        lon=72.378578
        num=57
    if(location=='Khajuraho'):
        lat=24.851900 
        lon=79.923000
        num=58
    if(location=='Gangtok'):
        lat=27.325757 
        lon=88.698277
        num=59
    if(location=='Dharuhera'):
        lat=28.205523 
        lon=76.795311
        num=60
    return num

In [34]:
df['Number']=df['location'].apply(lalong)
data= df[['Number','location']]
data.head()

   Number   location
0       2  Hyderabad
1       2  Hyderabad
2       2  Hyderabad
3       2  Hyderabad
4       2  Hyderabad

In [35]:
df.to_csv('upedit.csv')

In [36]:
df=df[df.latitude!=0]

In [37]:
df

,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition,latitude_long,latitude,longitude,Number
0,Andhra Pradesh,Hyderabad,RRO,3.90,14.10,108.833091,133.00000,40.791467,6/1/1990,1990,4.875,17.625,109.611030,122.000000,122,Unhealthy,17.387140,17.387140,78.491684,2
1,Andhra Pradesh,Hyderabad,I,5.60,11.80,108.833091,82.00000,40.791467,6/1/1990,1990,7.000,14.750,109.611030,-35.000000,109,Unhealthy,17.387140,17.387140,78.491684,2
2,Andhra Pradesh,Hyderabad,RRO,3.30,19.30,108.833091,111.00000,40.791467,6/1/1990,1990,4.125,24.125,109.611030,107.333333,109,Unhealthy,17.387140,17.387140,78.491684,2
3,Andhra Pradesh,Hyderabad,RRO,3.90,8.20,108.833091,118.00000,40.791467,7/1/1990,1990,4.875,10.250,109.611030,112.000000,112,Unhealthy,17.387140,17.387140,78.491684,2
4,Andhra Pradesh,Hyderabad,RRO,3.50,12.10,108.833091,135.00000,40.791467,7/1/1990,1990,4.375,15.125,109.611030,123.333333,123,Unhealthy,17.387140,17.387140,78.491684,2
5,Andhra Pradesh,Hyderabad,I,7.90,10.20,108.833091,80.00000,40.791467,7/1/1990,1990,9.875,12.750,109.611030,-37.500000,109,Unhealthy,17.387140,17.387140,78.491684,2
6,Andhra Pradesh,Hyderabad,I,12.40,11.50,108.833091,58.00000,40.791467,8/1/1990,1990,15.500,14.375,109.611030,-65.000000,109,Unhealthy,17.387140,17.387140,78.491684,2
7,Andhra Pradesh,Hyderabad,RRO,4.00,12.30,108.833091,99.00000,40.791467,8/1/1990,1990,5.000,15.375,109.611030,-13.750000,109,Unhealthy,17.387140,17.387140,78.491684,2
8,Andhra Pradesh,Hyderabad,RRO,6.30,11.50,108.833091,270.00000,40.791467,9/1/1990,1990,7.875,14.375,109.611030,220.000000,220,Hazardous,17.387140,17.387140,78.491684,2
9,Andhra Pradesh,Hyderabad,I,44.80,13.70,108.833091,97.00000,40.791467,9/1/1990,1990,56.000,17.125,109.611030,-16.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
10,Andhra Pradesh,Hyderabad,RRO,8.10,17.80,108.833091,167.00000,40.791467,9/1/1990,1990,10.125,22.250,109.611030,144.666667,144,Unhealthy,17.387140,17.387140,78.491684,2
11,Andhra Pradesh,Hyderabad,RRO,7.70,11.30,108.833091,145.00000,40.791467,10/1/1990,1990,9.625,14.125,109.611030,130.000000,130,Unhealthy,17.387140,17.387140,78.491684,2
12,Andhra Pradesh,Hyderabad,I,20.60,13.60,108.833091,75.00000,40.791467,10/1/1990,1990,25.750,17.000,109.611030,-43.750000,109,Unhealthy,17.387140,17.387140,78.491684,2
13,Andhra Pradesh,Hyderabad,RRO,13.90,7.20,108.833091,93.00000,40.791467,11/1/1990,1990,17.375,9.000,109.611030,-21.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
14,Andhra Pradesh,Hyderabad,I,11.20,18.60,108.833091,61.00000,40.791467,11/1/1990,1990,14.000,23.250,109.611030,-61.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
15,Andhra Pradesh,Hyderabad,RRO,22.30,35.90,108.833091,255.00000,40.791467,11/1/1990,1990,27.875,44.875,109.611030,205.000000,205,Hazardous,17.387140,17.387140,78.491684,2
16,Andhra Pradesh,Hyderabad,RRO,7.20,10.40,108.833091,148.00000,40.791467,1/1/1991,1991,9.000,13.000,109.611030,132.000000,132,Unhealthy,17.387140,17.387140,78.491684,2
17,Andhra Pradesh,Hyderabad,I,28.70,16.20,108.833091,77.00000,40.791467,1/1/1991,1991,35.875,20.250,109.611030,-41.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
18,Andhra Pradesh,Hyderabad,RRO,18.70,42.20,108.833091,125.00000,40.791467,2/1/1991,1991,23.375,85.250,109.611030,116.666667,116,Unhealthy,17.387140,17.387140,78.491684,2
19,Andhra Pradesh,Hyderabad,RRO,24.50,18.00,108.833091,330.00000,40.791467,2/1/1991,1991,30.625,22.500,109.611030,280.000000,280,Hazardous,17.387140,17.387140,78.491684,2
20,Andhra Pradesh,Hyderabad,I,20.40,12.60,108.833091,93.00000,40.791467,2/1/1991,1991,25.500,15.750,109.611030,-21.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
21,Andhra Pradesh,Hyderabad,RRO,5.20,41.30,108.833091,287.00000,40.791467,3/1/1991,1991,6.500,84.125,109.611030,237.000000,237,Hazardous,17.387140,17.387140,78.491684,2
22,Andhra Pradesh,Hyderabad,I,4.80,8.40,108.833091,85.00000,40.791467,3/1/1991,1991,6.000,10.500,109.611030,-31.250000,109,Unhealthy,17.387140,17.387140,78.491684,2
23,Andhra Pradesh,Hyderabad,RRO,9.70,12.40,108.833091,283.00000,40.791467,4/1/1991,1991,12.125,15.500,109.611030,233.000000,233,Hazardous,17.387140,17.387140,78.491684,2
24,Andhra Pradesh,Hyderabad,I,21.20,11.50,108.833091,108.00000,40.791467,4/1/1991,1991,26.500,14.375,109.611030,105.333333,109,Unhealthy,17.387140,17.387140,78.491684,2
25,Andhra Pradesh,Hyderabad,I,17.70,14.00,108.833091,121.00000,40.791467,5/1/1991,1991,22.125,17.500,109.611030,114.000000,114,Unhealthy,17.387140,17.387140,78.491684,2
26,Andhra Pradesh,Hyderabad,I,3.10,7.50,108.833091,84.00000,40.791467,6/1/1991,1991,3.875,9.375,109.611030,-32.500000,109,Unhealthy,17.387140,17.387140,78.491684,2
27,Andhra Pradesh,Hyderabad,RRO,3.00,19.00,108.833091,154.00000,40.791467,6/1/1991,1991,3.750,23.750,109.611030,136.000000,136,Unhealthy,17.387140,17.387140,78.491684,2
28,Andhra Pradesh,Hyderabad,RRO,6.20,10.00,108.833091,150.00000,40.791467,7/1/1991,1991,7.750,12.500,109.611030,133.333333,133,Unhealthy,17.387140,17.387140,78.491684,2
29,Andhra Pradesh,Hyderabad,I,7.90,9.20,108.833091,67.00000,40.791467,7/1/1991,1991,9.875,11.500,109.611030,-53.750000,109,Unhealthy,17.387140,17.387140,78.491684,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234113,Uttar Pradesh,Agra,S,2.00,18.00,113.000000,220.78348,40.791467,2/3/2014,2014,2.500,22.500,111.000000,180.522320,180,Very Unhealthy,27.176670,27.176670,78.008072,9
234114,Maharashtra,Nagpur,RRO,8.00,25.00,43.000000,220.78348,40.791467,10/16/2015,2015,10.000,31.250,53.750000,180.522320,180,Very Unhealthy,21.146633,21.146633,79.088860,6
234115,Telangana,Hyderabad,RRO,5.00,21.00,67.000000,220.78348,40.791467,10/20/2015,2015,6.250,26.250,83.750000,180.522320,180,Very Unhealthy,17.387140,17.387140,78.491684,2
234116,Delhi,Delhi,RRO,4.00,44.00,200.000000,220.78348,36.000000,8/12/2015,2015,5.000,87.500,140.000000,180.522320,180,Very Unhealthy,28.653229,28.653229,77.308601,3
234118,Gujarat,Ahmedabad,RRO,10.00,15.00,59.000000,220.78348,40.791467,1/16/2012,2012,12.500,18.750,73.750000,180.522320,180,Very Unhealthy,23.033863,23.033863,72.585022,14
234119,Punjab,Gobindgarh,RO,12.00,30.30,190.000000,220.78348,40.791467,12/14/2006,2006,15.000,37.875,136.666667,180.522320,180,Very Unhealthy,30.663738,30.663738,76.300042,22
234121,Assam,Guwahati,RO,7.00,23.00,169.000000,247.00000,40.791467,2/20/2008,2008,8.750,28.750,129.666667,198.000000,198,Very Unhealthy,26.148043,26.148043,91.731377,1
234123,Chandigarh,Chandigarh,I,2.00,36.00,125.000000,220.78348,40.791467,11/11/2013,2013,2.500,45.000,115.000000,180.522320,180,Very Unhealthy,30.741482,30.741482,76.768066,4
234124,Rajasthan,Alwar,RO,7.20,35.30,121.000000,241.00000,40.791467,3/12/2007,2007,9.000,44.125,113.666667,194.000000,194,Very Unhealthy,27.560932,27.560932,76.625015,24
234125,Rajasthan,Jaipur,I,18.50,28.10,108.833091,179.00000,40.791467,2/1/1996,1996,23.125,35.125,109.611030,152.666667,152,Very Unhealthy,26.922070,26.922070,75.778885,5
234126,Delhi,Delhi,RRO,5.00,112.00,306.000000,220.78348,40.791467,12/3/2015,2015,6.250,132.000,175.333333,180.522320,180,Very Unhealthy,28.653229,28.653229,77.308601,3
234127,Rajasthan,Jaipur,I,5.42,38.62,82.000000,230.00000,40.791467,12/6/2010,2010,6.775,48.275,100.666667,186.666667,186,Very Unhealthy,26.922070,26.922070,75.778885,5
234129,West Bengal,Howrah,RO,5.10,46.90,72.000000,187.00000,40.791467,2/5/2007,2007,6.375,91.125,90.000000,158.000000,158,Very Unhealthy,22.595770,22.595770,88.263641,27
234139,Maharashtra,Thane,RRO,28.00,64.00,149.000000,220.78348,40.791467,3/10/2015,2015,35.000,112.500,123.000000,180.522320,180,Very Unhealthy,19.218330,19.218330,72.978088,26
234142,Karnataka,Bangalore,RRO,19.00,33.00,384.000000,220.78348,40.791467,10/22/2014,2014,23.750,41.250,200.500000,180.522320,200,Very Unhealthy,12.972442,12.972442,77.580643,12
234145,Maharashtra,Nashik,RRO,25.00,33.00,96.000000,220.78348,40.791467,9/18/2014,2014,31.250,41.250,105.333333,180.522320,180,Very Unhealthy,19.997454,19.997454,73.789803,20
234146,Assam,Guwahati,RRO,8.00,15.00,187.000000,220.78348,40.791467,1/25/2013,2013,10.000,18.750,135.666667,180.522320,180,Very Unhealthy,26.148043,26.148043,91.731377,1
234147,Maharashtra,Nagpur,RRO,18.00,73.00,52.000000,220.78348,40.791467,1/1/2013,2013,22.500,123.750,65.000000,180.522320,180,Very Unhealthy,21.146633,21.146633,79.088860,6
234148,Punjab,Ludhiana,I,12.10,31.40,108.833091,220.78348,40.791467,4/1/2001,2001,15.125,39.250,109.611030,180.522320,180,Very Unhealthy,30.900965,30.900965,75.857277,16
234149,Maharashtra,Nashik,I,21.00,24.00,51.000000,220.78348,40.791467,8/16/2014,2014,26.250,30.000,63.750000,180.522320,180,Very Unhealthy,19.997454,19.997454,73.789803,20
234151,Punjab,Jalandhar,I,13.20,33.70,147.000000,220.78348,40.791467,4/28/2009,2009,16.500,42.125,122.333333,180.522320,180,Very Unhealthy,31.326015,31.326015,75.576180,23
234154,Maharashtra,Navi Mumbai,I,4.20,13.80,80.000000,220.78348,40.791467,7/27/2006,2006,5.250,17.250,100.000000,180.522320,180,Very Unhealthy,19.076090,19.076090,72.877426,18
234160,Punjab,Ludhiana,I,10.80,31.70,245.000000,220.78348,40.791467,9/4/2011,2011,13.500,39.625,155.000000,180.522320,180,Very Unhealthy,30.900965,30.900965,75.857277,16
234168,Karnataka,Bidar,RRO,7.00,13.00,58.000000,220.78348,40.791467,1/21/2015,2015,8.750,16.250,72.500000,180.522320,180,Very Unhealthy,17.920000,17.920000,77.519722,34
234170,Gujarat,Ahmedabad,RRO,15.00,28.00,81.000000,220.78348,40.791467,6/4/2011,2011,18.750,35.000,100.333333,180.522320,180,Very Unhealthy,23.033863,23.033863,72.585022,14
234172,Maharashtra,Navi Mumbai,I,20.00,49.00,150.000000,220.78348,40.791467,3/19/2012,2012,25.000,93.750,123.333333,180.522320,180,Very Unhealthy,19.076090,19.076090,72.877426,18
234175,West Bengal,Kolkata,RRO,3.00,36.00,63.000000,220.78348,34.000000,9/9/2015,2015,3.750,45.000,78.750000,180.522320,180,Very Unhealthy,22.572645,22.572645,88.363892,7
234177,Maharashtra,Pune,RRO,15.00,20.00,44.000000,220.78348,40.791467,6/26/2014,2014,18.750,25.000,55.000000,180.522320,180,Very Unhealthy,18.516726,18.516726,73.856255,19
234186,Rajasthan,Jodhpur,RRO,8.00,22.00,64.000000,219.00000,40.791467,9/22/2004,2004,10.000,27.500,80.000000,179.333333,179,Very Unhealthy,26.263863,26.263863,73.008957,17
234188,Rajasthan,Jodhpur,I,5.30,20.30,47.000000,238.00000,40.791467,7/10/2006,2006,6.625,25.375,58.750000,192.000000,192,Very Unhealthy,26.263863,26.263863,73.008957,17

In [39]:
mydf=df[df.Condition=='Hazardous']

In [40]:
mydf

,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition,latitude_long,latitude,longitude,Number
8,Andhra Pradesh,Hyderabad,RRO,6.3,11.5,108.833091,270.00000,40.791467,9/1/1990,1990,7.875000,14.375000,109.611030,220.000000,220,Hazardous,17.387140,17.387140,78.491684,2
15,Andhra Pradesh,Hyderabad,RRO,22.3,35.9,108.833091,255.00000,40.791467,11/1/1990,1990,27.875000,44.875000,109.611030,205.000000,205,Hazardous,17.387140,17.387140,78.491684,2
19,Andhra Pradesh,Hyderabad,RRO,24.5,18.0,108.833091,330.00000,40.791467,2/1/1991,1991,30.625000,22.500000,109.611030,280.000000,280,Hazardous,17.387140,17.387140,78.491684,2
21,Andhra Pradesh,Hyderabad,RRO,5.2,41.3,108.833091,287.00000,40.791467,3/1/1991,1991,6.500000,84.125000,109.611030,237.000000,237,Hazardous,17.387140,17.387140,78.491684,2
23,Andhra Pradesh,Hyderabad,RRO,9.7,12.4,108.833091,283.00000,40.791467,4/1/1991,1991,12.125000,15.500000,109.611030,233.000000,233,Hazardous,17.387140,17.387140,78.491684,2
44,Andhra Pradesh,Hyderabad,RRO,20.0,64.6,108.833091,353.00000,40.791467,1/1/1992,1992,25.000000,113.250000,109.611030,303.750000,303,Hazardous,17.387140,17.387140,78.491684,2
45,Andhra Pradesh,Hyderabad,RRO,35.8,12.5,108.833091,261.00000,40.791467,1/1/1992,1992,44.750000,15.625000,109.611030,211.000000,211,Hazardous,17.387140,17.387140,78.491684,2
49,Andhra Pradesh,Hyderabad,RRO,6.0,34.1,108.833091,271.00000,40.791467,1/1/1992,1992,7.500000,42.625000,109.611030,221.000000,221,Hazardous,17.387140,17.387140,78.491684,2
56,Andhra Pradesh,Hyderabad,RRO,24.9,61.0,108.833091,276.00000,40.791467,3/1/1992,1992,31.125000,108.750000,109.611030,226.000000,226,Hazardous,17.387140,17.387140,78.491684,2
63,Andhra Pradesh,Hyderabad,RRO,12.4,38.0,108.833091,267.00000,40.791467,3/1/1992,1992,15.500000,47.500000,109.611030,217.000000,217,Hazardous,17.387140,17.387140,78.491684,2
92,Andhra Pradesh,Hyderabad,RRO,17.4,31.7,108.833091,264.00000,40.791467,10/1/1992,1992,21.750000,39.625000,109.611030,214.000000,214,Hazardous,17.387140,17.387140,78.491684,2
95,Andhra Pradesh,Hyderabad,RRO,23.1,42.2,108.833091,314.00000,40.791467,11/1/1992,1992,28.875000,85.250000,109.611030,264.000000,264,Hazardous,17.387140,17.387140,78.491684,2
112,Andhra Pradesh,Hyderabad,RRO,8.7,8.5,108.833091,259.00000,40.791467,4/1/1994,1994,10.875000,10.625000,109.611030,209.000000,209,Hazardous,17.387140,17.387140,78.491684,2
125,Andhra Pradesh,Hyderabad,RRO,36.8,44.7,108.833091,262.00000,40.791467,12/1/1994,1994,46.000000,88.375000,109.611030,212.000000,212,Hazardous,17.387140,17.387140,78.491684,2
127,Andhra Pradesh,Hyderabad,RRO,20.0,59.4,108.833091,328.00000,40.791467,3/1/1995,1995,25.000000,106.750000,109.611030,278.000000,278,Hazardous,17.387140,17.387140,78.491684,2
128,Andhra Pradesh,Hyderabad,RRO,19.1,85.1,108.833091,251.00000,40.791467,4/1/1995,1995,23.875000,105.100000,109.611030,201.000000,201,Hazardous,17.387140,17.387140,78.491684,2
129,Andhra Pradesh,Hyderabad,RRO,44.3,192.4,108.833091,209.00000,40.791467,5/1/1995,1995,55.375000,212.400000,109.611030,172.666667,212,Hazardous,17.387140,17.387140,78.491684,2
130,Andhra Pradesh,Hyderabad,RRO,40.6,87.2,108.833091,362.00000,40.791467,11/1/1995,1995,50.750000,107.200000,109.611030,315.000000,315,Hazardous,17.387140,17.387140,78.491684,2
131,Andhra Pradesh,Hyderabad,RRO,22.7,41.6,108.833091,284.00000,40.791467,12/1/1995,1995,28.375000,84.500000,109.611030,234.000000,234,Hazardous,17.387140,17.387140,78.491684,2
154,Andhra Pradesh,Hyderabad,RRO,18.1,39.0,108.833091,251.00000,40.791467,3/1/1995,1995,22.625000,48.750000,109.611030,201.000000,201,Hazardous,17.387140,17.387140,78.491684,2
165,Andhra Pradesh,Hyderabad,RRO,14.4,26.8,108.833091,310.00000,40.791467,8/1/1995,1995,18.000000,33.500000,109.611030,260.000000,260,Hazardous,17.387140,17.387140,78.491684,2
166,Andhra Pradesh,Hyderabad,RRO,10.4,35.9,108.833091,270.00000,40.791467,1/1/1995,1995,13.000000,44.875000,109.611030,220.000000,220,Hazardous,17.387140,17.387140,78.491684,2
195,Andhra Pradesh,Hyderabad,RRO,23.9,29.8,108.833091,266.00000,40.791467,1/1/1996,1996,29.875000,37.250000,109.611030,216.000000,216,Hazardous,17.387140,17.387140,78.491684,2
205,Andhra Pradesh,Hyderabad,RRO,15.0,44.2,108.833091,280.00000,40.791467,3/1/1996,1996,18.750000,87.750000,109.611030,230.000000,230,Hazardous,17.387140,17.387140,78.491684,2
213,Andhra Pradesh,Hyderabad,RRO,12.3,15.5,108.833091,260.00000,40.791467,5/1/1996,1996,15.375000,19.375000,109.611030,210.000000,210,Hazardous,17.387140,17.387140,78.491684,2
220,Andhra Pradesh,Hyderabad,RRO,19.5,38.0,108.833091,331.00000,40.791467,7/1/1996,1996,24.375000,47.500000,109.611030,281.000000,281,Hazardous,17.387140,17.387140,78.491684,2
231,Andhra Pradesh,Hyderabad,RRO,13.2,15.9,108.833091,305.00000,40.791467,9/1/1996,1996,16.500000,19.875000,109.611030,255.000000,255,Hazardous,17.387140,17.387140,78.491684,2
237,Andhra Pradesh,Hyderabad,RRO,18.7,37.8,108.833091,279.00000,40.791467,10/1/1996,1996,23.375000,47.250000,109.611030,229.000000,229,Hazardous,17.387140,17.387140,78.491684,2
243,Andhra Pradesh,Hyderabad,RRO,19.8,55.1,108.833091,346.00000,40.791467,11/1/1996,1996,24.750000,101.375000,109.611030,296.000000,296,Hazardous,17.387140,17.387140,78.491684,2
250,Andhra Pradesh,Hyderabad,RRO,33.0,64.4,108.833091,276.00000,40.791467,12/1/1996,1996,41.250000,113.000000,109.611030,226.000000,226,Hazardous,17.387140,17.387140,78.491684,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159616,West Bengal,Kolkata,RRO,18.0,190.0,184.000000,220.78348,40.791467,1/17/2014,2014,22.500000,210.000000,134.666667,180.522320,210,Hazardous,22.572645,22.572645,88.363892,7
159617,West Bengal,Kolkata,RRO,23.0,228.0,113.000000,220.78348,40.791467,1/23/2014,2014,28.750000,248.000000,111.000000,180.522320,248,Hazardous,22.572645,22.572645,88.363892,7
159618,West Bengal,Kolkata,RRO,8.0,259.0,125.000000,220.78348,40.791467,5/2/2014,2014,10.000000,279.000000,115.000000,180.522320,279,Hazardous,22.572645,22.572645,88.363892,7
159619,West Bengal,Kolkata,RRO,15.0,194.0,103.000000,220.78348,40.791467,6/3/2014,2014,18.750000,214.000000,107.666667,180.522320,214,Hazardous,22.572645,22.572645,88.363892,7
159620,West Bengal,Kolkata,RRO,2.0,349.0,80.000000,220.78348,40.791467,11/4/2014,2014,2.500000,357.500000,100.000000,180.522320,357,Hazardous,22.572645,22.572645,88.363892,7
159621,West Bengal,Kolkata,RRO,10.0,182.0,116.000000,220.78348,40.791467,4/28/2014,2014,12.500000,202.000000,112.000000,180.522320,202,Hazardous,22.572645,22.572645,88.363892,7
159622,West Bengal,Kolkata,RRO,105.0,232.0,34.000000,220.78348,40.791467,8/9/2014,2014,108.333333,252.000000,42.500000,180.522320,252,Hazardous,22.572645,22.572645,88.363892,7
159623,West Bengal,Kolkata,RRO,3.0,181.0,29.000000,220.78348,40.791467,9/29/2014,2014,3.750000,201.000000,36.250000,180.522320,201,Hazardous,22.572645,22.572645,88.363892,7
159624,West Bengal,Kolkata,RRO,16.0,187.0,113.000000,220.78348,40.791467,11/13/2014,2014,20.000000,207.000000,111.000000,180.522320,207,Hazardous,22.572645,22.572645,88.363892,7
159625,West Bengal,Kolkata,RRO,9.0,194.0,168.000000,220.78348,40.791467,11/17/2014,2014,11.250000,214.000000,129.333333,180.522320,214,Hazardous,22.572645,22.572645,88.363892,7
159626,West Bengal,Kolkata,RRO,46.0,341.0,222.000000,220.78348,40.791467,10/12/2014,2014,57.500000,350.833333,147.333333,180.522320,350,Hazardous,22.572645,22.572645,88.363892,7
159630,West Bengal,Howrah,RRO,84.0,125.0,389.000000,220.78348,303.000000,11/11/2015,2015,101.333333,145.000000,201.125000,180.522320,201,Hazardous,22.595770,22.595770,88.263641,27
159631,West Bengal,Kolkata,I,39.0,263.0,220.000000,220.78348,40.791467,1/9/2015,2015,48.750000,283.000000,146.666667,180.522320,283,Hazardous,22.572645,22.572645,88.363892,7
159632,West Bengal,Kolkata,I,153.0,308.0,216.000000,220.78348,40.791467,1/12/2015,2015,124.333333,323.333333,145.333333,180.522320,323,Hazardous,22.572645,22.572645,88.363892,7
159633,West Bengal,Kolkata,I,97.0,211.0,315.000000,220.78348,40.791467,1/14/2015,2015,105.666667,231.000000,178.333333,180.522320,231,Hazardous,22.572645,22.572645,88.363892,7
159634,West Bengal,Kolkata,I,100.0,211.0,210.000000,220.78348,40.791467,1/16/2015,2015,106.666667,231.000000,143.333333,180.522320,231,Hazardous,22.572645,22.572645,88.363892,7
159635,West Bengal,Kolkata,I,122.0,233.0,192.000000,220.78348,40.791467,1/20/2015,2015,114.000000,253.000000,137.333333,180.522320,253,Hazardous,22.572645,22.572645,88.363892,7
159636,West Bengal,Kolkata,I,93.0,268.0,321.000000,220.78348,40.791467,2/3/2015,2015,104.333333,288.000000,180.333333,180.522320,288,Hazardous,22.572645,22.572645,88.363892,7
159637,West Bengal,Kolkata,I,119.0,206.0,178.000000,220.78348,40.791467,2/6/2015,2015,113.000000,226.000000,132.666667,180.522320,226,Hazardous,22.572645,22.572645,88.363892,7
159638,West Bengal,Kolkata,I,73.0,344.0,153.000000,220.78348,40.791467,2/10/2015,2015,91.250000,353.333333,124.333333,180.522320,353,Hazardous,22.572645,22.572645,88.363892,7
159639,West Bengal,Kolkata,I,57.0,319.0,190.000000,220.78348,40.791467,2/12/2015,2015,71.250000,332.500000,136.666667,180.522320,332,Hazardous,22.572645,22.572645,88.363892,7
159640,West Bengal,Kolkata,I,15.0,243.0,91.000000,220.78348,40.791467,2/17/2015,2015,18.750000,263.000000,103.666667,180.522320,263,Hazardous,22.572645,22.572645,88.363892,7
159641,West Bengal,Kolkata,I,27.0,190.0,160.000000,220.78348,40.791467,3/6/2015,2015,33.750000,210.000000,126.666667,180.522320,210,Hazardous,22.572645,22.572645,88.363892,7
159642,West Bengal,Kolkata,RRO,70.0,304.0,307.000000,220.78348,40.791467,1/24/2015,2015,87.500000,320.000000,175.666667,180.522320,320,Hazardous,22.572645,22.572645,88.363892,7
159643,West Bengal,Kolkata,RRO,98.0,235.0,157.000000,220.78348,40.791467,2/3/2015,2015,106.000000,255.000000,125.666667,180.522320,255,Hazardous,22.572645,22.572645,88.363892,7
159644,West Bengal,Kolkata,RRO,99.0,190.0,160.000000,220.78348,40.791467,1/12/2015,2015,106.333333,210.000000,126.666667,180.522320,210,Hazardous,22.572645,22.572645,88.363892,7
159645,West Bengal,Kolkata,RRO,21.0,225.0,231.000000,220.78348,40.791467,2/3/2015,2015,26.250000,245.000000,150.333333,180.522320,245,Hazardous,22.572645,22.572645,88.363892,7
159646,West Bengal,Kolkata,RRO,16.0,200.0,204.000000,220.78348,40.791467,2/9/2015,2015,20.000000,220.000000,141.333333,180.522320,220,Hazardous,22.572645,22.572645,88.363892,7
159647,West Bengal,Kolkata,RRO,27.0,190.0,68.000000,220.78348,40.791467,2/23/2015,2015,33.750000,210.000000,85.000000,180.522320,210,Hazardous,22.572645,22.572645,88.363892,7
159648,West Bengal,Kolkata,I,17.0,113.0,411.000000,220.78348,206.000000,11/11/2015,2015,21.250000,133.000000,203.875000,180.522320,203,Hazardous,22.572645,22.572645,88.363892,7

In [44]:
mydf.to_csv('azzar.csv')

In [3]:
# making data frame from csv file 
df = pd.read_csv("azzar.csv") 
# sorting by first name 
df=df.drop_duplicates(subset="location")

In [4]:
df.head()

,Unnamed: 0,state,location,type,so2,no2,rspm,spm,pm2_5,date,...,si,ni,rpi,spi,AQI,Condition,latitude_long,latitude,longitude,Number
0,8,Andhra Pradesh,Hyderabad,RRO,6.3,11.5,108.833091,270.0,40.791467,9/1/1990,...,7.875,14.375,109.611030,220.00,220,Hazardous,17.387140,17.387140,78.491684,2
2279,8441,Assam,Guwahati,RRO,15.7,46.1,108.833091,330.0,40.791467,10/1/1993,...,19.625,90.125,109.611030,280.00,280,Hazardous,26.148043,26.148043,91.731377,1
3030,13158,Assam,Silchar,RO,5.8,16.3,207.000000,383.0,40.791467,2/4/2009,...,7.250,20.375,142.333333,341.25,341,Hazardous,24.833946,24.833946,92.779282,40
3039,14662,Chandigarh,Chandigarh,I,11.3,29.7,108.833091,318.0,40.791467,5/1/1989,...,14.125,37.125,109.611030,268.00,268,Hazardous,30.741482,30.741482,76.768066,4
4344,21134,Delhi,Delhi,R,8.6,16.2,108.833091,323.0,40.791467,1/9/1987,...,10.750,20.250,109.611030,273.00,273,Hazardous,28.653229,28.653229,77.308601,3

In [6]:
df.to_csv('plmap.csv')