In [10]:
import pandas as pd

In [11]:
df=pd.read_csv('final.csv')

In [12]:
df.head()

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,0,0,Andhra Pradesh,Hyderabad,RRO,4.8,17.4,108.833091,220.78348,40.791467,1990-02-01,1990,6.000,21.750,109.61103,180.52232,180,Very Unhealthy
1,1,1,Andhra Pradesh,Hyderabad,I,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01,1990,3.875,8.750,109.61103,180.52232,180,Very Unhealthy
2,2,2,Andhra Pradesh,Hyderabad,RRO,6.2,28.5,108.833091,220.78348,40.791467,1990-02-01,1990,7.750,35.625,109.61103,180.52232,180,Very Unhealthy
3,3,3,Andhra Pradesh,Hyderabad,RRO,6.3,14.7,108.833091,220.78348,40.791467,1990-03-01,1990,7.875,18.375,109.61103,180.52232,180,Very Unhealthy
4,4,4,Andhra Pradesh,Hyderabad,I,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01,1990,5.875,9.375,109.61103,180.52232,180,Very Unhealthy

In [13]:
df.drop_duplicates(subset=['Condition'])

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,0,0,Andhra Pradesh,Hyderabad,RRO,4.8,17.4,108.833091,220.78348,40.791467,1990-02-01,1990,6.000,21.750,109.61103,180.52232,180,Very Unhealthy
11,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.00000,40.791467,1990-06-01,1990,4.875,17.625,109.61103,122.00000,122,Unhealthy
20,20,20,Andhra Pradesh,Hyderabad,RRO,6.3,11.5,108.833091,270.00000,40.791467,1990-09-01,1990,7.875,14.375,109.61103,220.00000,220,Hazardous
1090,1090,1090,Andhra Pradesh,Hyderabad,I,4.8,22.4,32.700000,97.70000,40.791467,2004-07-26,2004,6.000,28.000,40.87500,-15.37500,40,Good
1169,1169,1169,Andhra Pradesh,Hyderabad,I,4.1,52.9,37.300000,98.00000,40.791467,2004-03-05,2004,5.125,98.625,46.62500,-15.00000,98,Moderate

In [14]:
df.tail()

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
435730,435730,435734,West Bengal,ULUBERIA,RIRUO,20.0,44.0,148.0,220.78348,40.791467,2015-12-15,2015,25.00,87.50,122.666667,180.52232,180,Very Unhealthy
435731,435731,435735,West Bengal,ULUBERIA,RIRUO,17.0,44.0,131.0,220.78348,40.791467,2015-12-18,2015,21.25,87.50,117.000000,180.52232,180,Very Unhealthy
435732,435732,435736,West Bengal,ULUBERIA,RIRUO,18.0,45.0,140.0,220.78348,40.791467,2015-12-21,2015,22.50,88.75,120.000000,180.52232,180,Very Unhealthy
435733,435733,435737,West Bengal,ULUBERIA,RIRUO,22.0,50.0,143.0,220.78348,40.791467,2015-12-24,2015,27.50,95.00,121.000000,180.52232,180,Very Unhealthy
435734,435734,435738,West Bengal,ULUBERIA,RIRUO,20.0,46.0,171.0,220.78348,40.791467,2015-12-29,2015,25.00,90.00,130.333333,180.52232,180,Very Unhealthy

In [15]:
data=df['Condition'].value_counts()

In [16]:
data

Very Unhealthy    276086
Hazardous          68569
Unhealthy          58885
Good               17117
Moderate           15078
Name: Condition, dtype: int64

In [17]:
my_dataframe = df[df.Condition == 'Very Unhealthy']

In [8]:
my_dataframe.to_csv('vuh.csv')

In [18]:
city =df['location'].value_counts()
city

Guwahati            9984
Hyderabad           9667
Delhi               8551
Chandigarh          8520
Jaipur              7850
Nagpur              7829
Kolkata             7733
Kanpur              7545
Agra                7306
Kochi               7263
Visakhapatnam       7108
Bangalore           6659
Chennai             6646
Ahmedabad           6256
Lucknow             6194
Ludhiana            6175
Jodhpur             6035
Navi Mumbai         5541
Pune                5179
Nashik              5145
Chandrapur          4780
Kota                4181
Gobindgarh          3976
Jalandhar           3784
Alwar               3746
Udaipur             3741
Thane               3620
Howrah              3601
Parwanoo            3523
Aizawl              3499
                    ...
DANKUNI              103
Faridkot              97
Kothur                96
Hoshiarpur            88
Bidar                 88
Mathura               78
Konark                78
Chandarpur            77
Imphal                76
Keonjhar              76
Silchar               75
Umsning               68
Bijapur               68
Puri                  58
MORBI                 46
Saharanpur            46
Baruipur              45
Naharlagun            45
Itanagar              45
Turicorin             41
Chittorgarh           36
Noida, Ghaziabad      27
Nizamabad             27
VAPI                  24
Sarigam               24
Bhuj                  24
SANAND                23
Khajuraho             16
Gangtok                1
Dharuhera              1
Name: location, Length: 304, dtype: int64

In [19]:
my_dataframe

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,0,0,Andhra Pradesh,Hyderabad,RRO,4.8,17.4,108.833091,220.78348,40.791467,1990-02-01,1990,6.000,21.750,109.611030,180.522320,180,Very Unhealthy
1,1,1,Andhra Pradesh,Hyderabad,I,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01,1990,3.875,8.750,109.611030,180.522320,180,Very Unhealthy
2,2,2,Andhra Pradesh,Hyderabad,RRO,6.2,28.5,108.833091,220.78348,40.791467,1990-02-01,1990,7.750,35.625,109.611030,180.522320,180,Very Unhealthy
3,3,3,Andhra Pradesh,Hyderabad,RRO,6.3,14.7,108.833091,220.78348,40.791467,1990-03-01,1990,7.875,18.375,109.611030,180.522320,180,Very Unhealthy
4,4,4,Andhra Pradesh,Hyderabad,I,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01,1990,5.875,9.375,109.611030,180.522320,180,Very Unhealthy
5,5,5,Andhra Pradesh,Hyderabad,RRO,6.4,25.7,108.833091,220.78348,40.791467,1990-03-01,1990,8.000,32.125,109.611030,180.522320,180,Very Unhealthy
6,6,6,Andhra Pradesh,Hyderabad,RRO,5.4,17.1,108.833091,220.78348,40.791467,1990-04-01,1990,6.750,21.375,109.611030,180.522320,180,Very Unhealthy
7,7,7,Andhra Pradesh,Hyderabad,I,4.7,8.7,108.833091,220.78348,40.791467,1990-04-01,1990,5.875,10.875,109.611030,180.522320,180,Very Unhealthy
8,8,8,Andhra Pradesh,Hyderabad,RRO,4.2,23.0,108.833091,220.78348,40.791467,1990-04-01,1990,5.250,28.750,109.611030,180.522320,180,Very Unhealthy
9,9,9,Andhra Pradesh,Hyderabad,I,4.0,8.9,108.833091,220.78348,40.791467,1990-05-01,1990,5.000,11.125,109.611030,180.522320,180,Very Unhealthy
10,10,10,Andhra Pradesh,Hyderabad,RRO,3.6,18.6,108.833091,220.78348,40.791467,1990-05-01,1990,4.500,23.250,109.611030,180.522320,180,Very Unhealthy
17,17,17,Andhra Pradesh,Hyderabad,RRO,4.0,9.9,108.833091,179.00000,40.791467,1990-08-01,1990,5.000,12.375,109.611030,152.666667,152,Very Unhealthy
25,25,25,Andhra Pradesh,Hyderabad,RRO,20.4,27.5,108.833091,212.00000,40.791467,1990-10-01,1990,25.500,34.375,109.611030,174.666667,174,Very Unhealthy
29,29,29,Andhra Pradesh,Hyderabad,RRO,24.5,28.0,108.833091,197.00000,40.791467,1991-01-01,1991,30.625,35.000,109.611030,164.666667,164,Very Unhealthy
36,36,36,Andhra Pradesh,Hyderabad,RRO,7.5,12.2,108.833091,241.00000,40.791467,1991-03-01,1991,9.375,15.250,109.611030,194.000000,194,Very Unhealthy
38,38,38,Andhra Pradesh,Hyderabad,RRO,8.5,48.5,108.833091,220.78348,40.791467,1991-04-01,1991,10.625,93.125,109.611030,180.522320,180,Very Unhealthy
41,41,41,Andhra Pradesh,Hyderabad,RRO,4.9,15.3,108.833091,234.00000,40.791467,1991-05-01,1991,6.125,19.125,109.611030,189.333333,189,Very Unhealthy
43,43,43,Andhra Pradesh,Hyderabad,RRO,12.3,38.6,108.833091,219.00000,40.791467,1991-05-01,1991,15.375,48.250,109.611030,179.333333,179,Very Unhealthy
44,44,44,Andhra Pradesh,Hyderabad,RRO,3.5,11.9,108.833091,179.00000,40.791467,1991-06-01,1991,4.375,14.875,109.611030,152.666667,152,Very Unhealthy
61,61,61,Andhra Pradesh,Hyderabad,RRO,18.8,39.0,108.833091,232.00000,40.791467,1991-11-01,1991,23.500,48.750,109.611030,188.000000,188,Very Unhealthy
64,64,64,Andhra Pradesh,Hyderabad,RRO,6.0,47.0,108.833091,242.00000,40.791467,1991-12-01,1991,7.500,91.250,109.611030,194.666667,194,Very Unhealthy
66,66,66,Andhra Pradesh,Hyderabad,RRO,14.6,4.4,108.833091,190.00000,40.791467,1992-01-01,1992,18.250,5.500,109.611030,160.000000,160,Very Unhealthy
69,69,69,Andhra Pradesh,Vishakhapatnam,RRO,55.8,33.8,108.833091,245.00000,40.791467,1992-01-01,1992,69.750,42.250,109.611030,196.666667,196,Very Unhealthy
73,73,73,Andhra Pradesh,Hyderabad,RRO,12.9,14.7,108.833091,180.00000,40.791467,1992-01-01,1992,16.125,18.375,109.611030,153.333333,153,Very Unhealthy
75,75,75,Andhra Pradesh,Hyderabad,RRO,13.0,66.5,108.833091,241.00000,40.791467,1992-02-01,1992,16.250,115.625,109.611030,194.000000,194,Very Unhealthy
79,79,79,Andhra Pradesh,Vishakhapatnam,RRO,24.3,18.7,108.833091,201.00000,40.791467,1992-02-01,1992,30.375,23.375,109.611030,167.333333,167,Very Unhealthy
80,80,80,Andhra Pradesh,Vishakhapatnam,RRO,36.1,18.1,108.833091,250.00000,40.791467,1992-02-01,1992,45.125,22.625,109.611030,200.000000,200,Very Unhealthy
81,81,81,Andhra Pradesh,Vishakhapatnam,RRO,34.5,21.0,108.833091,227.00000,40.791467,1992-02-01,1992,43.125,26.250,109.611030,184.666667,184,Very Unhealthy
84,84,84,Andhra Pradesh,Hyderabad,RRO,14.1,37.8,108.833091,248.00000,40.791467,1992-02-01,1992,17.625,47.250,109.611030,198.666667,198,Very Unhealthy
89,89,89,Andhra Pradesh,Vishakhapatnam,RRO,67.4,127.7,108.833091,215.00000,40.791467,1992-03-01,1992,84.250,147.700,109.611030,176.666667,176,Very Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435705,435705,435709,West Bengal,ULUBERIA,RIRUO,11.0,36.0,86.000000,220.78348,40.791467,2015-09-17,2015,13.750,45.000,102.000000,180.522320,180,Very Unhealthy
435706,435706,435710,West Bengal,ULUBERIA,RIRUO,18.0,48.0,162.000000,220.78348,40.791467,2015-09-23,2015,22.500,92.500,127.333333,180.522320,180,Very Unhealthy
435707,435707,435711,West Bengal,ULUBERIA,RIRUO,12.0,42.0,107.000000,220.78348,40.791467,2015-09-26,2015,15.000,85.000,109.000000,180.522320,180,Very Unhealthy
435708,435708,435712,West Bengal,ULUBERIA,RIRUO,12.0,38.0,103.000000,220.78348,40.791467,2015-09-29,2015,15.000,47.500,107.666667,180.522320,180,Very Unhealthy
435709,435709,435713,West Bengal,ULUBERIA,RIRUO,14.0,36.0,113.000000,220.78348,40.791467,2015-10-03,2015,17.500,45.000,111.000000,180.522320,180,Very Unhealthy
435710,435710,435714,West Bengal,ULUBERIA,RIRUO,20.0,41.0,131.000000,220.78348,40.791467,2015-10-08,2015,25.000,83.750,117.000000,180.522320,180,Very Unhealthy
435711,435711,435715,West Bengal,ULUBERIA,RIRUO,10.0,38.0,88.000000,220.78348,40.791467,2015-10-11,2015,12.500,47.500,102.666667,180.522320,180,Very Unhealthy
435712,435712,435716,West Bengal,ULUBERIA,RIRUO,12.0,40.0,116.000000,220.78348,40.791467,2015-10-13,2015,15.000,50.000,112.000000,180.522320,180,Very Unhealthy
435713,435713,435717,West Bengal,ULUBERIA,RIRUO,21.0,52.0,134.000000,220.78348,40.791467,2015-10-17,2015,26.250,97.500,118.000000,180.522320,180,Very Unhealthy
435714,435714,435718,West Bengal,ULUBERIA,RIRUO,21.0,49.0,178.000000,220.78348,40.791467,2015-10-19,2015,26.250,93.750,132.666667,180.522320,180,Very Unhealthy
435715,435715,435719,West Bengal,ULUBERIA,RIRUO,18.0,47.0,138.000000,220.78348,40.791467,2015-10-23,2015,22.500,91.250,119.333333,180.522320,180,Very Unhealthy
435716,435716,435720,West Bengal,ULUBERIA,RIRUO,19.0,45.0,126.000000,220.78348,40.791467,2015-10-28,2015,23.750,88.750,115.333333,180.522320,180,Very Unhealthy
435717,435717,435721,West Bengal,ULUBERIA,RIRUO,11.0,34.0,90.000000,220.78348,40.791467,2015-10-31,2015,13.750,42.500,103.333333,180.522320,180,Very Unhealthy
435718,435718,435722,West Bengal,ULUBERIA,RIRUO,16.0,40.0,135.000000,220.78348,40.791467,2015-11-05,2015,20.000,50.000,118.333333,180.522320,180,Very Unhealthy
435719,435719,435723,West Bengal,ULUBERIA,RIRUO,15.0,37.0,136.000000,220.78348,40.791467,2015-11-07,2015,18.750,46.250,118.666667,180.522320,180,Very Unhealthy
435720,435720,435724,West Bengal,ULUBERIA,RIRUO,22.0,67.0,202.000000,220.78348,40.791467,2015-11-10,2015,27.500,116.250,140.666667,180.522320,180,Very Unhealthy
435721,435721,435725,West Bengal,ULUBERIA,RIRUO,20.0,64.0,181.000000,220.78348,40.791467,2015-11-11,2015,25.000,112.500,133.666667,180.522320,180,Very Unhealthy
435722,435722,435726,West Bengal,ULUBERIA,RIRUO,14.0,42.0,95.000000,220.78348,40.791467,2015-11-16,2015,17.500,85.000,105.000000,180.522320,180,Very Unhealthy
435723,435723,435727,West Bengal,ULUBERIA,RIRUO,11.0,34.0,118.000000,220.78348,40.791467,2015-11-20,2015,13.750,42.500,112.666667,180.522320,180,Very Unhealthy
435724,435724,435728,West Bengal,ULUBERIA,RIRUO,17.0,43.0,144.000000,220.78348,40.791467,2015-11-26,2015,21.250,86.250,121.333333,180.522320,180,Very Unhealthy
435725,435725,435729,West Bengal,ULUBERIA,RIRUO,19.0,49.0,140.000000,220.78348,40.791467,2015-11-29,2015,23.750,93.750,120.000000,180.522320,180,Very Unhealthy
435726,435726,435730,West Bengal,ULUBERIA,RIRUO,18.0,41.0,142.000000,220.78348,40.791467,2015-12-03,2015,22.500,83.750,120.666667,180.522320,180,Very Unhealthy
435727,435727,435731,West Bengal,ULUBERIA,RIRUO,22.0,58.0,155.000000,220.78348,40.791467,2015-12-06,2015,27.500,105.000,125.000000,180.522320,180,Very Unhealthy
435728,435728,435732,West Bengal,ULUBERIA,RIRUO,22.0,50.0,145.000000,220.78348,40.791467,2015-12-09,2015,27.500,95.000,121.666667,180.522320,180,Very Unhealthy
435729,435729,435733,West Bengal,ULUBERIA,RIRUO,34.0,61.0,161.000000,220.78348,40.791467,2015-12-12,2015,42.500,108.750,127.000000,180.522320,180,Very Unhealthy
435730,435730,435734,West Bengal,ULUBERIA,RIRUO,20.0,44.0,148.000000,220.78348,40.791467,2015-12-15,2015,25.000,87.500,122.666667,180.522320,180,Very Unhealthy
435731,435731,435735,West Bengal,ULUBERIA,RIRUO,17.0,44.0,131.000000,220.78348,40.791467,2015-12-18,2015,21.250,87.500,117.000000,180.522320,180,Very Unhealthy
435732,435732,435736,West Bengal,ULUBERIA,RIRUO,18.0,45.0,140.000000,220.78348,40.791467,2015-12-21,2015,22.500,88.750,120.000000,180.522320,180,Very Unhealthy
435733,435733,435737,West Bengal,ULUBERIA,RIRUO,22.0,50.0,143.000000,220.78348,40.791467,2015-12-24,2015,27.500,95.000,121.000000,180.522320,180,Very Unhealthy
435734,435734,435738,West Bengal,ULUBERIA,RIRUO,20.0,46.0,171.000000,220.78348,40.791467,2015-12-29,2015,25.000,90.000,130.333333,180.522320,180,Very Unhealthy

In [20]:
df=df[df.Condition != 'Very Unhealthy']

In [21]:
df.head()

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
11,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.0,40.791467,1990-06-01,1990,4.875,17.625,109.61103,122.000000,122,Unhealthy
12,12,12,Andhra Pradesh,Hyderabad,I,5.6,11.8,108.833091,82.0,40.791467,1990-06-01,1990,7.000,14.750,109.61103,-35.000000,109,Unhealthy
13,13,13,Andhra Pradesh,Hyderabad,RRO,3.3,19.3,108.833091,111.0,40.791467,1990-06-01,1990,4.125,24.125,109.61103,107.333333,109,Unhealthy
14,14,14,Andhra Pradesh,Hyderabad,RRO,3.9,8.2,108.833091,118.0,40.791467,1990-07-01,1990,4.875,10.250,109.61103,112.000000,112,Unhealthy
15,15,15,Andhra Pradesh,Hyderabad,RRO,3.5,12.1,108.833091,135.0,40.791467,1990-07-01,1990,4.375,15.125,109.61103,123.333333,123,Unhealthy

In [22]:
import random

In [23]:
df1 = my_dataframe.sample(frac =.27)

In [24]:
df1

,Unnamed: 0,Unnamed: 0.1,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
144552,144552,144552,Karnataka,Bangalore,RRO,15.65,30.80,165.000000,220.78348,40.791467,2012-05-10,2012,19.5625,38.5000,128.333333,180.522320,180,Very Unhealthy
113849,113849,113849,Himachal Pradesh,Parwanoo,I,3.90,19.80,93.000000,178.00000,40.791467,2009-12-17,2009,4.8750,24.7500,104.333333,152.000000,152,Very Unhealthy
393720,393720,393724,Uttar Pradesh,Lucknow,RRO,9.00,34.00,202.000000,220.78348,40.791467,2011-11-28,2011,11.2500,42.5000,140.666667,180.522320,180,Very Unhealthy
6422,6422,6422,Andhra Pradesh,Visakhapatnam,RO,9.70,31.20,105.000000,206.00000,40.791467,2007-04-12,2007,12.1250,39.0000,108.333333,170.666667,170,Very Unhealthy
174918,174918,174919,Kerala,Kochi,RRO,2.00,17.00,58.000000,220.78348,40.791467,2015-12-22,2015,2.5000,21.2500,72.500000,180.522320,180,Very Unhealthy
150120,150120,150121,Karnataka,Shimoga,I,4.00,8.00,20.000000,220.78348,40.791467,2014-03-07,2014,5.0000,10.0000,25.000000,180.522320,180,Very Unhealthy
249594,249594,249597,Maharashtra,Pune,RRO,16.00,22.00,33.000000,220.78348,40.791467,2014-06-18,2014,20.0000,27.5000,41.250000,180.522320,180,Very Unhealthy
252177,252177,252180,Maharashtra,Thane,I,26.00,58.00,83.000000,220.78348,40.791467,2015-09-12,2015,32.5000,105.0000,101.000000,180.522320,180,Very Unhealthy
135702,135702,135702,Karnataka,Bangalore,I,22.40,22.00,108.833091,220.00000,40.791467,1990-10-01,1990,28.0000,27.5000,109.611030,180.000000,180,Very Unhealthy
354017,354017,354021,Tamil Nadu,Coimbatore,RRO,4.00,21.00,67.000000,220.78348,40.791467,2011-02-21,2011,5.0000,26.2500,83.750000,180.522320,180,Very Unhealthy
431239,431239,431243,West Bengal,Kolkata,RRO,34.00,74.00,156.000000,220.78348,40.791467,2013-08-03,2013,42.5000,125.0000,125.333333,180.522320,180,Very Unhealthy
228198,228198,228199,Maharashtra,Nashik,I,30.00,30.00,96.000000,220.78348,40.791467,2011-06-04,2011,37.5000,37.5000,105.333333,180.522320,180,Very Unhealthy
245325,245325,245327,Maharashtra,Chandrapur,RRO,11.00,51.00,89.000000,220.78348,40.791467,2014-03-20,2014,13.7500,96.2500,103.000000,180.522320,180,Very Unhealthy
284385,284385,284389,Odisha,Berhampur,RRO,2.00,14.00,40.000000,220.78348,40.791467,2014-08-25,2014,2.5000,17.5000,50.000000,180.522320,180,Very Unhealthy
19920,19920,19920,Andhra Pradesh,Tirupati,S,4.00,9.00,40.000000,220.78348,40.791467,2013-02-14,2013,5.0000,11.2500,50.000000,180.522320,180,Very Unhealthy
313734,313734,313738,Punjab,Jalandhar,RRO,13.00,25.00,152.000000,220.78348,40.791467,2014-10-01,2014,16.2500,31.2500,124.000000,180.522320,180,Very Unhealthy
308783,308783,308787,Punjab,Jalandhar,RRO,14.00,24.00,131.000000,220.78348,40.791467,2012-03-16,2012,17.5000,30.0000,117.000000,180.522320,180,Very Unhealthy
3776,3776,3776,Andhra Pradesh,Vijayawada,I,5.30,30.40,79.000000,204.00000,40.791467,2006-06-23,2006,6.6250,38.0000,98.750000,169.333333,169,Very Unhealthy
193758,193758,193759,Madhya Pradesh,Dewas,RRO,16.00,23.00,84.000000,220.78348,40.791467,2014-05-20,2014,20.0000,28.7500,101.333333,180.522320,180,Very Unhealthy
359583,359583,359587,Tamil Nadu,Chennai,RRO,15.00,18.00,73.000000,220.78348,40.791467,2014-03-20,2014,18.7500,22.5000,91.250000,180.522320,180,Very Unhealthy
367746,367746,367750,Telangana,Hyderabad,I,6.00,37.00,134.000000,220.78348,40.791467,2015-05-21,2015,7.5000,46.2500,118.000000,180.522320,180,Very Unhealthy
149936,149936,149937,Karnataka,Mysore,RRO,12.00,23.00,43.000000,220.78348,40.791467,2014-12-08,2014,15.0000,28.7500,53.750000,180.522320,180,Very Unhealthy
32542,32542,32542,Assam,Bongaigaon,RRO,8.00,18.00,56.000000,220.78348,40.791467,2010-11-01,2010,10.0000,22.5000,70.000000,180.522320,180,Very Unhealthy
361654,361654,361658,Tamil Nadu,Trichy,RRO,19.00,22.00,132.000000,220.78348,40.791467,2014-10-03,2014,23.7500,27.5000,117.333333,180.522320,180,Very Unhealthy
273249,273249,273252,Odisha,Rourkela,RO,4.60,9.80,138.000000,249.00000,40.791467,2006-01-14,2006,5.7500,12.2500,119.333333,199.333333,199,Very Unhealthy
60888,60888,60888,Chhattisgarh,Bhilai,I,9.00,27.00,137.000000,220.78348,40.791467,2010-07-07,2010,11.2500,33.7500,119.000000,180.522320,180,Very Unhealthy
21693,21693,21693,Andhra Pradesh,Chittoor,S,5.00,14.00,74.000000,220.78348,40.791467,2014-06-22,2014,6.2500,17.5000,92.500000,180.522320,180,Very Unhealthy
116783,116783,116783,Himachal Pradesh,Kala Amb,RRO,2.00,14.00,96.000000,220.78348,40.791467,2011-01-22,2011,2.5000,17.5000,105.333333,180.522320,180,Very Unhealthy
79173,79173,79173,Goa,Vasco,I,7.00,8.00,154.000000,220.78348,40.791467,2015-12-29,2015,8.7500,10.0000,124.666667,180.522320,180,Very Unhealthy
402680,402680,402684,Uttar Pradesh,Agra,S,2.00,5.00,140.000000,220.78348,40.791467,2014-01-06,2014,2.5000,6.2500,120.000000,180.522320,180,Very Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126789,126789,126789,Himachal Pradesh,Kala Amb,RRO,2.00,13.00,79.000000,220.78348,40.791467,2015-02-28,2015,2.5000,16.2500,98.750000,180.522320,180,Very Unhealthy
177173,177173,177174,Kerala,Malappuram,I,2.00,16.00,49.000000,220.78348,40.791467,2015-10-25,2015,2.5000,20.0000,61.250000,180.522320,180,Very Unhealthy
232482,232482,232483,Maharashtra,Jalna,I,8.00,29.00,131.000000,220.78348,40.791467,2012-03-01,2012,10.0000,36.2500,117.000000,180.522320,180,Very Unhealthy
95139,95139,95139,Gujarat,Vapi,RRO,12.00,20.00,61.000000,220.78348,40.791467,2010-09-20,2010,15.0000,25.0000,76.250000,180.522320,180,Very Unhealthy
360308,360308,360312,Tamil Nadu,Coimbatore,RRO,4.00,27.00,38.000000,220.78348,40.791467,2014-08-14,2014,5.0000,33.7500,47.500000,180.522320,180,Very Unhealthy
126037,126037,126037,Himachal Pradesh,Paonta Sahib,I,2.00,14.00,218.000000,220.78348,40.791467,2015-11-06,2015,2.5000,17.5000,146.000000,180.522320,180,Very Unhealthy
152483,152483,152484,Karnataka,Bidar,RRO,7.00,13.00,58.000000,220.78348,40.791467,2015-01-21,2015,8.7500,16.2500,72.500000,180.522320,180,Very Unhealthy
229663,229663,229664,Maharashtra,Sangli,RRO,13.00,59.00,84.000000,220.78348,40.791467,2011-12-16,2011,16.2500,106.2500,101.333333,180.522320,180,Very Unhealthy
95401,95401,95401,Gujarat,Ahmedabad,RRO,15.00,28.00,81.000000,220.78348,40.791467,2011-06-04,2011,18.7500,35.0000,100.333333,180.522320,180,Very Unhealthy
127230,127230,127230,Himachal Pradesh,Sunder Nagar,RRO,2.00,13.00,87.000000,220.78348,40.791467,2015-02-13,2015,2.5000,16.2500,102.333333,180.522320,180,Very Unhealthy
235519,235519,235520,Maharashtra,Navi Mumbai,I,20.00,49.00,150.000000,220.78348,40.791467,2012-03-19,2012,25.0000,93.7500,123.333333,180.522320,180,Very Unhealthy
16735,16735,16735,Andhra Pradesh,Visakhapatnam,RRO,19.00,28.00,167.000000,220.78348,40.791467,2012-07-16,2012,23.7500,35.0000,129.000000,180.522320,180,Very Unhealthy
254331,254331,254334,Maharashtra,Amravati,RRO,13.00,14.00,127.000000,220.78348,40.791467,2015-03-04,2015,16.2500,17.5000,115.666667,180.522320,180,Very Unhealthy
434247,434247,434251,West Bengal,Kolkata,RRO,3.00,36.00,63.000000,220.78348,34.000000,2015-09-09,2015,3.7500,45.0000,78.750000,180.522320,180,Very Unhealthy
234327,234327,234328,Maharashtra,Nanded,RRO,18.00,19.00,27.000000,220.78348,40.791467,2012-03-10,2012,22.5000,23.7500,33.750000,180.522320,180,Very Unhealthy
249205,249205,249208,Maharashtra,Pune,RRO,15.00,20.00,44.000000,220.78348,40.791467,2014-06-26,2014,18.7500,25.0000,55.000000,180.522320,180,Very Unhealthy
80498,80498,80498,Goa,Kundaim,I,4.00,10.00,73.000000,220.78348,29.000000,2015-11-04,2015,5.0000,12.5000,91.250000,180.522320,180,Very Unhealthy
19633,19633,19633,Andhra Pradesh,Rajahmundry,I,11.00,15.00,74.000000,220.78348,40.791467,2013-12-27,2013,13.7500,18.7500,92.500000,180.522320,180,Very Unhealthy
181573,181573,181574,Madhya Pradesh,Indore,RO,10.40,17.00,121.000000,219.00000,40.791467,2006-05-01,2006,13.0000,21.2500,113.666667,179.333333,179,Very Unhealthy
435153,435153,435157,West Bengal,Kalyani,RIRUO,2.00,25.00,45.000000,220.78348,40.791467,2015-05-29,2015,2.5000,31.2500,56.250000,180.522320,180,Very Unhealthy
94125,94125,94125,Gujarat,Ankleshwar,RRO,13.00,21.00,75.000000,220.78348,40.791467,2010-02-11,2010,16.2500,26.2500,93.750000,180.522320,180,Very Unhealthy
425806,425806,425810,West Bengal,Raniganj,I,9.20,69.00,112.000000,247.00000,40.791467,2010-11-05,2010,11.5000,118.7500,110.666667,198.000000,198,Very Unhealthy
176676,176676,176677,Kerala,Pathanamthitta,RRO,2.00,15.00,26.000000,220.78348,40.791467,2015-07-30,2015,2.5000,18.7500,32.500000,180.522320,180,Very Unhealthy
263460,263460,263463,Mizoram,Aizawl,RRO,2.00,7.00,74.000000,220.78348,40.791467,2012-07-24,2012,2.5000,8.7500,92.500000,180.522320,180,Very Unhealthy
320765,320765,320769,Rajasthan,Jodhpur,RRO,8.00,22.00,64.000000,219.00000,40.791467,2004-09-22,2004,10.0000,27.5000,80.000000,179.333333,179,Very Unhealthy
25627,25627,25627,Andhra Pradesh,Chittoor,RRO,5.00,11.00,59.000000,220.78348,40.791467,2015-12-05,2015,6.2500,13.7500,73.750000,180.522320,180,Very Unhealthy
324803,324803,324807,Rajasthan,Jodhpur,I,5.30,20.30,47.000000,238.00000,40.791467,2006-07-10,2006,6.6250,25.3750,58.750000,192.000000,192,Very Unhealthy
122213,122213,122213,Himachal Pradesh,Paonta Sahib,I,2.00,16.00,107.000000,220.78348,40.791467,2013-08-01,2013,2.5000,20.0000,109.000000,180.522320,180,Very Unhealthy
280693,280693,280696,Odisha,Balasore,RRO,2.00,11.33,81.670000,220.78348,40.791467,2012-04-23,2012,2.5000,14.1625,100.556667,180.522320,180,Very Unhealthy
291592,291592,291596,Puducherry,Karaikal,I,14.00,9.00,25.000000,220.78348,40.791467,2014-08-27,2014,17.5000,11.2500,31.250000,180.522320,180,Very Unhealthy

In [25]:
pieces = {'x': df, 'y': df1}

In [26]:
df_piece = pd.concat(pieces)

In [27]:
df_piece

          Unnamed: 0  Unnamed: 0.1             state        location   type  \
x 11              11            11    Andhra Pradesh       Hyderabad    RRO
  12              12            12    Andhra Pradesh       Hyderabad      I
  13              13            13    Andhra Pradesh       Hyderabad    RRO
  14              14            14    Andhra Pradesh       Hyderabad    RRO
  15              15            15    Andhra Pradesh       Hyderabad    RRO
  16              16            16    Andhra Pradesh       Hyderabad      I
  18              18            18    Andhra Pradesh       Hyderabad      I
  19              19            19    Andhra Pradesh       Hyderabad    RRO
  20              20            20    Andhra Pradesh       Hyderabad    RRO
  21              21            21    Andhra Pradesh       Hyderabad      I
  22              22            22    Andhra Pradesh       Hyderabad    RRO
  23              23            23    Andhra Pradesh       Hyderabad    RRO
  24              24            24    Andhra Pradesh       Hyderabad      I
  26              26            26    Andhra Pradesh       Hyderabad    RRO
  27              27            27    Andhra Pradesh       Hyderabad      I
  28              28            28    Andhra Pradesh       Hyderabad    RRO
  30              30            30    Andhra Pradesh       Hyderabad    RRO
  31              31            31    Andhra Pradesh       Hyderabad      I
  32              32            32    Andhra Pradesh       Hyderabad    RRO
  33              33            33    Andhra Pradesh       Hyderabad    RRO
  34              34            34    Andhra Pradesh       Hyderabad      I
  35              35            35    Andhra Pradesh       Hyderabad    RRO
  37              37            37    Andhra Pradesh       Hyderabad      I
  39              39            39    Andhra Pradesh       Hyderabad    RRO
  40              40            40    Andhra Pradesh       Hyderabad      I
  42              42            42    Andhra Pradesh       Hyderabad      I
  45              45            45    Andhra Pradesh       Hyderabad      I
  46              46            46    Andhra Pradesh       Hyderabad    RRO
  47              47            47    Andhra Pradesh       Hyderabad    RRO
  48              48            48    Andhra Pradesh       Hyderabad      I
...              ...           ...               ...             ...    ...
y 126789      126789        126789  Himachal Pradesh        Kala Amb    RRO
  177173      177173        177174            Kerala      Malappuram      I
  232482      232482        232483       Maharashtra           Jalna      I
  95139        95139         95139           Gujarat            Vapi    RRO
  360308      360308        360312        Tamil Nadu      Coimbatore    RRO
  126037      126037        126037  Himachal Pradesh    Paonta Sahib      I
  152483      152483        152484         Karnataka           Bidar    RRO
  229663      229663        229664       Maharashtra          Sangli    RRO
  95401        95401         95401           Gujarat       Ahmedabad    RRO
  127230      127230        127230  Himachal Pradesh    Sunder Nagar    RRO
  235519      235519        235520       Maharashtra     Navi Mumbai      I
  16735        16735         16735    Andhra Pradesh   Visakhapatnam    RRO
  254331      254331        254334       Maharashtra        Amravati    RRO
  434247      434247        434251       West Bengal         Kolkata    RRO
  234327      234327        234328       Maharashtra          Nanded    RRO
  249205      249205        249208       Maharashtra            Pune    RRO
  80498        80498         80498               Goa         Kundaim      I
  19633        19633         19633    Andhra Pradesh     Rajahmundry      I
  181573      181573        181574    Madhya Pradesh          Indore     RO
  435153      435153        435157       West Bengal         Kalyani  RIRUO
  94125        94125         94125           Gujarat      Ankleshwar    RRO
  425806      425806        425810       West Bengal        Raniganj      I
  176676      176676        176677            Kerala  Pathanamthitta    RRO
  263460      263460        263463           Mizoram          Aizawl    RRO
  320765      320765        320769         Rajasthan         Jodhpur    RRO
  25627        25627         25627    Andhra Pradesh        Chittoor    RRO
  324803      324803        324807         Rajasthan         Jodhpur      I
  122213      122213        122213  Himachal Pradesh    Paonta Sahib      I
  280693      280693        280696            Odisha        Balasore    RRO
  291592      291592        291596        Puducherry        Karaikal      I

           so2    no2        rspm        spm      pm2_5        date  year  \
x 11       3.9  14.10  108.833091  133.00000  40.791467  1990-06-01  1990
  12       5.6  11.80  108.833091   82.00000  40.791467  1990-06-01  1990
  13       3.3  19.30  108.833091  111.00000  40.791467  1990-06-01  1990
  14       3.9   8.20  108.833091  118.00000  40.791467  1990-07-01  1990
  15       3.5  12.10  108.833091  135.00000  40.791467  1990-07-01  1990
  16       7.9  10.20  108.833091   80.00000  40.791467  1990-07-01  1990
  18      12.4  11.50  108.833091   58.00000  40.791467  1990-08-01  1990
  19       4.0  12.30  108.833091   99.00000  40.791467  1990-08-01  1990
  20       6.3  11.50  108.833091  270.00000  40.791467  1990-09-01  1990
  21      44.8  13.70  108.833091   97.00000  40.791467  1990-09-01  1990
  22       8.1  17.80  108.833091  167.00000  40.791467  1990-09-01  1990
  23       7.7  11.30  108.833091  145.00000  40.791467  1990-10-01  1990
  24      20.6  13.60  108.833091   75.00000  40.791467  1990-10-01  1990
  26      13.9   7.20  108.833091   93.00000  40.791467  1990-11-01  1990
  27      11.2  18.60  108.833091   61.00000  40.791467  1990-11-01  1990
  28      22.3  35.90  108.833091  255.00000  40.791467  1990-11-01  1990
  30       7.2  10.40  108.833091  148.00000  40.791467  1991-01-01  1991
  31      28.7  16.20  108.833091   77.00000  40.791467  1991-01-01  1991
  32      18.7  42.20  108.833091  125.00000  40.791467  1991-02-01  1991
  33      24.5  18.00  108.833091  330.00000  40.791467  1991-02-01  1991
  34      20.4  12.60  108.833091   93.00000  40.791467  1991-02-01  1991
  35       5.2  41.30  108.833091  287.00000  40.791467  1991-03-01  1991
  37       4.8   8.40  108.833091   85.00000  40.791467  1991-03-01  1991
  39       9.7  12.40  108.833091  283.00000  40.791467  1991-04-01  1991
  40      21.2  11.50  108.833091  108.00000  40.791467  1991-04-01  1991
  42      17.7  14.00  108.833091  121.00000  40.791467  1991-05-01  1991
  45       3.1   7.50  108.833091   84.00000  40.791467  1991-06-01  1991
  46       3.0  19.00  108.833091  154.00000  40.791467  1991-06-01  1991
  47       6.2  10.00  108.833091  150.00000  40.791467  1991-07-01  1991
  48       7.9   9.20  108.833091   67.00000  40.791467  1991-07-01  1991
...        ...    ...         ...        ...        ...         ...   ...
y 126789   2.0  13.00   79.000000  220.78348  40.791467  2015-02-28  2015
  177173   2.0  16.00   49.000000  220.78348  40.791467  2015-10-25  2015
  232482   8.0  29.00  131.000000  220.78348  40.791467  2012-03-01  2012
  95139   12.0  20.00   61.000000  220.78348  40.791467  2010-09-20  2010
  360308   4.0  27.00   38.000000  220.78348  40.791467  2014-08-14  2014
  126037   2.0  14.00  218.000000  220.78348  40.791467  2015-11-06  2015
  152483   7.0  13.00   58.000000  220.78348  40.791467  2015-01-21  2015
  229663  13.0  59.00   84.000000  220.78348  40.791467  2011-12-16  2011
  95401   15.0  28.00   81.000000  220.78348  40.791467  2011-06-04  2011
  127230   2.0  13.00   87.000000  220.78348  40.791467  2015-02-13  2015
  235519  20.0  49.00  150.000000  220.78348  40.791467  2012-03-19  2012
  16735   19.0  28.00  167.000000  220.78348  40.791467  2012-07-16  2012
  254331  13.0  14.00  127.000000  220.78348  40.791467  2015-03-04  2015
  434247   3.0  36.00   63.000000  220.78348  34.000000  2015-09-09  2015
  234327  18.0  19.00   27.000000  220.78348  40.791467  2012-03-10  2012
  249205  15.0  20.00   44.000000  220.78348  40.791467  2014-06-26  2014
  80498    4.0  10.00   73.000000  220.78348  29.000000  2015-11-04  2015
  19633   11.0  15.00   74.000000  220.78348  40.791467  2013-12-27  2013
  181573  10.4  17.00  121.000000  219.00000  40.791467  2006-05-01  2006
  435153   2.0  25.00   45.000000  220.78348  40.791467  2015-05-29  2015
  94125   13.0  21.00   75.000000  220.78348  40.791467  2010-02-11  2010
  425806   9.2  69.00  112.000000  247.00000  40.791467  2010-11-05  2010
  176676   2.0  15.00   26.000000  220.78348  40.791467  2015-07-30  2015
  263460   2.0   7.00   74.000000  220.78348  40.791467  2012-07-24  2012
  320765   8.0  22.00   64.000000  219.00000  40.791467  2004-09-22  2004
  25627    5.0  11.00   59.000000  220.78348  40.791467  2015-12-05  2015
  324803   5.3  20.30   47.000000  238.00000  40.791467  2006-07-10  2006
  122213   2.0  16.00  107.000000  220.78348  40.791467  2013-08-01  2013
  280693   2.0  11.33   81.670000  220.78348  40.791467  2012-04-23  2012
  291592  14.0   9.00   25.000000  220.78348  40.791467  2014-08-27  2014

              si        ni         rpi         spi  AQI       Condition
x 11       4.875   17.6250  109.611030  122.000000  122       Unhealthy
  12       7.000   14.7500  109.611030  -35.000000  109       Unhealthy
  13       4.125   24.1250  109.611030  107.333333  109       Unhealthy
  14       4.875   10.2500  109.611030  112.000000  112       Unhealthy
  15       4.375   15.1250  109.611030  123.333333  123       Unhealthy
  16       9.875   12.7500  109.611030  -37.500000  109       Unhealthy
  18      15.500   14.3750  109.611030  -65.000000  109       Unhealthy
  19       5.000   15.3750  109.611030  -13.750000  109       Unhealthy
  20       7.875   14.3750  109.611030  220.000000  220       Hazardous
  21      56.000   17.1250  109.611030  -16.250000  109       Unhealthy
  22      10.125   22.2500  109.611030  144.666667  144       Unhealthy
  23       9.625   14.1250  109.611030  130.000000  130       Unhealthy
  24      25.750   17.0000  109.611030  -43.750000  109       Unhealthy
  26      17.375    9.0000  109.611030  -21.250000  109       Unhealthy
  27      14.000   23.2500  109.611030  -61.250000  109       Unhealthy
  28      27.875   44.8750  109.611030  205.000000  205       Hazardous
  30       9.000   13.0000  109.611030  132.000000  132       Unhealthy
  31      35.875   20.2500  109.611030  -41.250000  109       Unhealthy
  32      23.375   85.2500  109.611030  116.666667  116       Unhealthy
  33      30.625   22.5000  109.611030  280.000000  280       Hazardous
  34      25.500   15.7500  109.611030  -21.250000  109       Unhealthy
  35       6.500   84.1250  109.611030  237.000000  237       Hazardous
  37       6.000   10.5000  109.611030  -31.250000  109       Unhealthy
  39      12.125   15.5000  109.611030  233.000000  233       Hazardous
  40      26.500   14.3750  109.611030  105.333333  109       Unhealthy
  42      22.125   17.5000  109.611030  114.000000  114       Unhealthy
  45       3.875    9.3750  109.611030  -32.500000  109       Unhealthy
  46       3.750   23.7500  109.611030  136.000000  136       Unhealthy
  47       7.750   12.5000  109.611030  133.333333  133       Unhealthy
  48       9.875   11.5000  109.611030  -53.750000  109       Unhealthy
...          ...       ...         ...         ...  ...             ...
y 126789   2.500   16.2500   98.750000  180.522320  180  Very Unhealthy
  177173   2.500   20.0000   61.250000  180.522320  180  Very Unhealthy
  232482  10.000   36.2500  117.000000  180.522320  180  Very Unhealthy
  95139   15.000   25.0000   76.250000  180.522320  180  Very Unhealthy
  360308   5.000   33.7500   47.500000  180.522320  180  Very Unhealthy
  126037   2.500   17.5000  146.000000  180.522320  180  Very Unhealthy
  152483   8.750   16.2500   72.500000  180.522320  180  Very Unhealthy
  229663  16.250  106.2500  101.333333  180.522320  180  Very Unhealthy
  95401   18.750   35.0000  100.333333  180.522320  180  Very Unhealthy
  127230   2.500   16.2500  102.333333  180.522320  180  Very Unhealthy
  235519  25.000   93.7500  123.333333  180.522320  180  Very Unhealthy
  16735   23.750   35.0000  129.000000  180.522320  180  Very Unhealthy
  254331  16.250   17.5000  115.666667  180.522320  180  Very Unhealthy
  434247   3.750   45.0000   78.750000  180.522320  180  Very Unhealthy
  234327  22.500   23.7500   33.750000  180.522320  180  Very Unhealthy
  249205  18.750   25.0000   55.000000  180.522320  180  Very Unhealthy
  80498    5.000   12.5000   91.250000  180.522320  180  Very Unhealthy
  19633   13.750   18.7500   92.500000  180.522320  180  Very Unhealthy
  181573  13.000   21.2500  113.666667  179.333333  179  Very Unhealthy
  435153   2.500   31.2500   56.250000  180.522320  180  Very Unhealthy
  94125   16.250   26.2500   93.750000  180.522320  180  Very Unhealthy
  425806  11.500  118.7500  110.666667  198.000000  198  Very Unhealthy
  176676   2.500   18.7500   32.500000  180.522320  180  Very Unhealthy
  263460   2.500    8.7500   92.500000  180.522320  180  Very Unhealthy
  320765  10.000   27.5000   80.000000  179.333333  179  Very Unhealthy
  25627    6.250   13.7500   73.750000  180.522320  180  Very Unhealthy
  324803   6.625   25.3750   58.750000  192.000000  192  Very Unhealthy
  122213   2.500   20.0000  109.000000  180.522320  180  Very Unhealthy
  280693   2.500   14.1625  100.556667  180.522320  180  Very Unhealthy
  291592  17.500   11.2500   31.250000  180.522320  180  Very Unhealthy

[234192 rows x 18 columns]

In [28]:
df_piece.to_csv('updat.csv')

In [33]:
df=pd.read_csv('updat.csv')

In [34]:
df.head()

,hello,Unnamed: 1,Rohit,Kohli,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,x,11,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.0,40.791467,6/1/1990,1990,4.875,17.625,109.61103,122.000000,122,Unhealthy
1,x,12,12,12,Andhra Pradesh,Hyderabad,I,5.6,11.8,108.833091,82.0,40.791467,6/1/1990,1990,7.000,14.750,109.61103,-35.000000,109,Unhealthy
2,x,13,13,13,Andhra Pradesh,Hyderabad,RRO,3.3,19.3,108.833091,111.0,40.791467,6/1/1990,1990,4.125,24.125,109.61103,107.333333,109,Unhealthy
3,x,14,14,14,Andhra Pradesh,Hyderabad,RRO,3.9,8.2,108.833091,118.0,40.791467,7/1/1990,1990,4.875,10.250,109.61103,112.000000,112,Unhealthy
4,x,15,15,15,Andhra Pradesh,Hyderabad,RRO,3.5,12.1,108.833091,135.0,40.791467,7/1/1990,1990,4.375,15.125,109.61103,123.333333,123,Unhealthy

In [37]:
df=df.drop(['hello','Kohli'],axis=1)

In [38]:
df.head()

,Unnamed: 1,Rohit,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.0,40.791467,6/1/1990,1990,4.875,17.625,109.61103,122.000000,122,Unhealthy
1,12,12,Andhra Pradesh,Hyderabad,I,5.6,11.8,108.833091,82.0,40.791467,6/1/1990,1990,7.000,14.750,109.61103,-35.000000,109,Unhealthy
2,13,13,Andhra Pradesh,Hyderabad,RRO,3.3,19.3,108.833091,111.0,40.791467,6/1/1990,1990,4.125,24.125,109.61103,107.333333,109,Unhealthy
3,14,14,Andhra Pradesh,Hyderabad,RRO,3.9,8.2,108.833091,118.0,40.791467,7/1/1990,1990,4.875,10.250,109.61103,112.000000,112,Unhealthy
4,15,15,Andhra Pradesh,Hyderabad,RRO,3.5,12.1,108.833091,135.0,40.791467,7/1/1990,1990,4.375,15.125,109.61103,123.333333,123,Unhealthy

In [40]:
df.to_csv('updat.csv')

In [41]:
df=pd.read_csv('updat.csv')

In [42]:
df.head()

,Unnamed: 0,Unnamed: 1,ro,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,0,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.0,40.791467,6/1/1990,1990,4.875,17.625,109.61103,122.000000,122,Unhealthy
1,1,12,12,Andhra Pradesh,Hyderabad,I,5.6,11.8,108.833091,82.0,40.791467,6/1/1990,1990,7.000,14.750,109.61103,-35.000000,109,Unhealthy
2,2,13,13,Andhra Pradesh,Hyderabad,RRO,3.3,19.3,108.833091,111.0,40.791467,6/1/1990,1990,4.125,24.125,109.61103,107.333333,109,Unhealthy
3,3,14,14,Andhra Pradesh,Hyderabad,RRO,3.9,8.2,108.833091,118.0,40.791467,7/1/1990,1990,4.875,10.250,109.61103,112.000000,112,Unhealthy
4,4,15,15,Andhra Pradesh,Hyderabad,RRO,3.5,12.1,108.833091,135.0,40.791467,7/1/1990,1990,4.375,15.125,109.61103,123.333333,123,Unhealthy

In [45]:
df.head()

,Unnamed: 0,Unnamed: 1,ro,state,location,type,so2,no2,rspm,spm,pm2_5,date,year,si,ni,rpi,spi,AQI,Condition
0,0,11,11,Andhra Pradesh,Hyderabad,RRO,3.9,14.1,108.833091,133.0,40.791467,6/1/1990,1990,4.875,17.625,109.61103,122.000000,122,Unhealthy
1,1,12,12,Andhra Pradesh,Hyderabad,I,5.6,11.8,108.833091,82.0,40.791467,6/1/1990,1990,7.000,14.750,109.61103,-35.000000,109,Unhealthy
2,2,13,13,Andhra Pradesh,Hyderabad,RRO,3.3,19.3,108.833091,111.0,40.791467,6/1/1990,1990,4.125,24.125,109.61103,107.333333,109,Unhealthy
3,3,14,14,Andhra Pradesh,Hyderabad,RRO,3.9,8.2,108.833091,118.0,40.791467,7/1/1990,1990,4.875,10.250,109.61103,112.000000,112,Unhealthy
4,4,15,15,Andhra Pradesh,Hyderabad,RRO,3.5,12.1,108.833091,135.0,40.791467,7/1/1990,1990,4.375,15.125,109.61103,123.333333,123,Unhealthy